export const ITEM_KINDS = ["app", "script", "opensource"] as const;
export const PUBLISH_STATUSES = ["draft", "published"] as const;
export const SOURCE_KINDS = ["official", "opensource", "discount"] as const;
export const PLATFORMS = ["windows", "macos", "linux"] as const;
export const SLUG_PATTERN = /^[a-z0-9][a-z0-9-]{0,99}$/;
export const MAX_UPLOAD = 5 * 1024 * 1024;

export function isHttpUrl(value: string, allowHttp = false): boolean {
  if (!value || value.length > 2048) return false;
  try {
    const url = new URL(value);
    return !url.username && !url.password && (url.protocol === "https:" || (allowHttp && url.protocol === "http:"));
  } catch {
    return false;
  }
}

export function imageExtension(type: string, data: Uint8Array): string | undefined {
  const starts = (...bytes: number[]) => bytes.every((byte, index) => data[index] === byte);
  const text = (start: number, end: number) => Buffer.from(data.subarray(start, end)).toString("ascii");
  if (type === "image/jpeg" && starts(0xff, 0xd8, 0xff)) return "jpg";
  if (type === "image/png" && starts(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a)) return "png";
  if (type === "image/gif" && ["GIF87a", "GIF89a"].includes(text(0, 6))) return "gif";
  if (type === "image/webp" && text(0, 4) === "RIFF" && text(8, 12) === "WEBP") return "webp";
  return undefined;
}

/** Only paths generated by the upload flow can be removed or served. */
export function mediaParts(value: string): [string, string] | undefined {
  const match = /^\/media\/([a-z0-9][a-z0-9-]{0,99})\/([a-f0-9]{16}\.(?:jpe?g|png|webp|gif))$/.exec(value);
  return match ? [match[1], match[2]] : undefined;
}
